### ISSUE TITLE
error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’

### ISSUE THREAD

**Issue by josea210** [servomac/mitro#1]
Error execute command  ./build.sh  in  cd ../browser-ext/api/

> webworker-threads@0.6.0 install /srv/mitro/browser-ext/api/build/node/lib/node_modules/webworker-threads
> node-gyp rebuild

make: Entering directory `/srv/mitro/browser-ext/api/build/node/lib/node_modules/webworker-threads/build'
  CXX(target) Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o
In file included from ../src/WebWorkerThreads.cc:12:
../node_modules/nan/nan.h:316: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
make: Leaving directory`/srv/mitro/browser-ext/api/build/node/lib/node_modules/webworker-threads/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/mitro/browser-ext/api/build/node/lib/node_modules/webworker-threads
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by servomac** [comment]
Thanks for reporting this. Could you try with  `npm -g install npm` just before calling build.sh?
